# for module compiling
import os
Import('RTT_ROOT')

cwd = str(Dir('#'))
objs = []
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

objs += SConscript(cwd + "/../STM32F2xx_Libraries/SConscript")
objs += SConscript(cwd + "/../../../../common/SConscript")

Return('objs')
