#ifndef MINECONTROLLER_MENULIBCHINESE_H
#define MINECONTROLLER_MENULIBCHINESE_H

#define LOG_CHINA                     "翌日科技"
#define NONWK_CHINA                   "无网络"

#define FUNCTIONLIST_CHINA       "功 能"
#define CONTACTLIST_CHINA        "通讯录"
#define CHECK_CHINA  "查看"
#define ADD_CHINA      "增加"
#define CALLRECORD_CHINA         "通话记录"
#define SHORTMESSAGE_CHINA       "短信息"
#define SMS_INCOMINGBOX_CHINA    "收件箱"
#define SMS_WRITINGBOX_CHINA      "写信息"
#define SMS_TEMPLATE_CHINA      "模板"
#define SHORTMESSAGE_DRAFT_CHINA     "草稿箱"
#define ClOCK_CHINA                 "时钟"
#define CLOCKFORMAT_CHINA    "时间格式"
#define CALENDAR_CHINA           "日历"
#define MISSED_CALL_CHINA        "未接来电"
#define DIALED_CALL_CHINA        "已拨电话"
#define ANSWERED_CALL_CHINA      "已接来电"
#define INCOMING_CHINA           "来电"
#define VOICING_CHINA            "正在通话"
#define CALLING_CHINA            "正在呼叫..."
#define NWK_INIT_CHINA           "搜索网络..."
#define MISSED_CALL_MENU_CHINA   "个未接电话"
#define NO_POWER_CHINA           "电池电量低"
#define SETTINGS_CHINA           "正在设置..."
#define TOOLS_CHINA              "附加功能"

#define RINGSETTING_CHINA   	"提示音设置"
#define TIMESETTING_CHINA   	"时间设置"
#define BACKLIGHTSETTING_CHINA  "背光设置"
#define PADLOCKSETTING_CHINA    "自动键盘锁"
#define RESTOREDEFAULT_CHINA    "恢复出厂设置"
#define BACKLIGHTTIME_CHINA  "背光时间"
#define BELLSETTING_CHINA   	"铃声设置"
#define SMSBELLSETTING_CHINA  "信息提示声"
#define VOLSETTING_CHINA     "铃声音量"
#define SHAKESETTING_CHINA     "振动提示"   	
#define VOLUME_CHINA            "音量"
#define ALARMCLOCK_CHINA     "闹钟"

#define DELETERECORD_CHINA 		 "删除记录"
#define DELETE_ALL_CHINA         "删除全部"
#define DELETE_MISSEDCALL_CHINA     "未接来电?"
#define DELETE_ANSWEREDCALL_CHINA  "已接来电?"
#define DELETE_DIALEDCALL_CHINA  "已拨电话?"

#define DELETED_CHINA     "已删除"
#define SETTED_CHINA      "设置完成"

#define TIME_CHINA 				"时间"
#define DATE_CHINA 				"日期"
#define TIMEFORMAT_CHINA        "时间格式"
#define TIMEFORMAT24_CHINA      "24小时制"
#define TIMEFORMAT12_CHINA      "12小时制"
#define TODAYIS_CHINA               "今天是"

#define SECONDS_5_CHINA      "5秒"
#define SECONDS_10_CHINA     "10秒"
#define SECONDS_20_CHINA     "20秒"
#define NOLIMIT_CHINA    "无限"

#define OPENLOCK_CHINA       "开 锁"
#define REQUESTSTAR_CHINA  "请按*键"
#define HOWTOUNLOCK1_CHINA   "先按开锁键"
#define HOWTOUNLOCK2_CHINA   "再按*键"

#define OPEN_CHINA               "开"
#define CLOSE_CHINA              "关"

#define IS_RESTORE_DEFAULT_CHINA "恢复默认设置?"
#define CONFIRM_CHINA   "确认"
#define CANCEL_CHINA    "取消"
#define NAME_CHINA "姓名"
#define NUM_CHINA "号码"
#define INPUT_NUM_CHINA "输入号码"
#define EMPTY_CONTACTLIST_CHINA "通讯录为空"
#define FULL_CONTACTLIST_CHINA   "通讯录已满"
#define EMPTY_CALLRECORD_CHINA "通话记录为空"
#define EMPTY_SMSINBOX_CHINA "收件箱为空"
#define SMS_WRITING_FULL_CHINA "短消息输入已满"
#define NAME_INPUT_FULL_CHINA "姓名输入已满"
#define SAVE_CHINA "存储"
#define BACK_CHINA "返回"
#define DELETE_CHINA "删除"
#define PINYIN_CHINA "拼音"
#define PUNCTUATION_CHINA "标点"
#define NUMBER_CHINA "数字"
#define ENGLISH_CHINA "英文"
#define SM_SENDING_CHINA "发送信息..."
#define SM_SENDING_SUCCESS_CHINA "信息发送成功"
#define SM_SENDING_FAIL_CHINA "信息发送失败"
#define SMS_READ_CHINA              "阅读"
#define SMS_REPLY_CHINA             "回复"
#define SMS_SEND_CHINA              "发送"
#define SMS_EDIT_CHINA             "编辑"
#define NEW_SMS_CHINA             "新信息"
#define SMS_DELETE_CHINA "删除此信息?"

#define SMS_TEMPLATE_1             "瓦斯浓度为:"
#define SMS_TEMPLATE_2             "二氧化碳浓度:"
#define SMS_TEMPLATE_3             "一氧化碳浓度:"
#define SMS_TEMPLATE_4             "氧气浓度:"
#define SMS_TEMPLATE_5             "氢气浓度:"

#ifdef MENU_RF_DEBUG
#define SET_CHANNEL_CHINA        "频道设置"
#define SET_PANID_CHINA            "PANID设置"
#define INPUT_CHANNEL_CHINA    "请输入频道:"
#define INPUT_PANID_CHINA        "请输入PANID:"
#define INVALID_CHANNEL_CHINA        "非法的频道"
#define INVALID_PANID_CHINA        "非法的PANID"
#endif

#define STATIONDETECT_CH    "分站检测"
#define CARDDETECT_CH        "标识卡检测"
#define PHONEDETECT_CH      "手机检测"
#define STATIONSETTING_CH   "分站设置"
#define CARDSETTING_CH      "标识卡设置"
#define CHANNEL_SELECT_CH "频道选择"
#define LABELCALBRATE_CH   "定标"
#define INPUT_CARDID_CHINA "请输入卡号:"
#define INPUT_SUBSTATIONPANID_CHINA "请输入分站PANID:"

#define CARD_SLEEPTIME_CH      "休眠时间(毫秒)"
#define CARD_POLLINTERVAL_CH      "请求数据频率"
#define CARD_POLLTIMEOUT_CH      "响应时间(毫秒)"
#define CARD_CHANNEL_CH      "频道"
#define CARD_INVALID_DATA_CH      "非法数据!"

#endif
