#ifndef _GENERAL_DATA_TYPE_DEF_H_
#define _GENERAL_DATA_TYPE_DEF_H_

#define COMM_ENTIRE_NET_GENERAL 1000
//for schedular
#define COMM_ENTIRE_NET_SCHEDULAR_SMS 2000
#define COMM_ENTIRE_NET_SCHEDULAR_FORCE_CLOSE 2001

#define NET_PORT_WEIGHT 1

#endif

