Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []

if GetDepend('PROJECT_LPBSS_V2') == True:
    CPPPATH = [cwd + '/ground/ground_v2']
elif GetDepend('PROJECT_LPBSS_V1_5_1') == True:
    src += ['crc.c']
    CPPPATH = [cwd + '/ground/']
    CPPPATH += [cwd, str(Dir('#'))]
else:
    src	+= Glob('*.c')
    CPPPATH = [cwd, str(Dir('#'))]
    CPPPATH += [cwd + '/2g']

CPPPATH += [cwd + '/../']

group = DefineGroup('protocol', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
